name: Build nginx-micro 贝壳云专用
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu make

      - name: Build
        run: |
          make CC=aarch64-linux-gnu-gcc

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: nginx-micro-beikeyun
          path: nginx-micro
