name: Build nginx-micro for 贝壳云 aarch64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install cross compiler
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-aarch64-linux-gnu make

      - name: Compile nginx-micro
        run: |
          make CC=aarch64-linux-gnu-gcc
          file nginx-micro

      - name: Upload final file
        uses: actions/upload-artifact@v4
        with:
          name: nginx-micro-beikeyun-aarch64
          path: nginx-micro
